server:
  port: 8080
  servlet:
    context-path: /sql

spring:
  application:
    name: "code-generate"         # 程序name，建议配置，方便统一的服务管理

  # mysql连接信息配置
  datasource:
    url: jdbc:mysql://10.2.5.2:3306/assets?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&socketTimeout=2000&connectTimeout=2000&rewriteBatchedStatements=true&useSSL=false&serverTimezone=Asia/Shanghai&useSSL=false
    username: beinet
    password: beinet.cn
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    default-property-inclusion: always  #为空也序列化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    mapper:
      accept_case_insensitive_properties: true

  ldap:
    urls: ldap://beinet.cn:389
    username: cn=ldapauth,${spring.ldap.base}
    password: beinet.cn
    base: OU=OrgUnit,DC=beinet,DC=cn

logging:
  level:
    cn.beinet.codegenerate.configs.LdapLoginFilter: debug

backup:
  localDir: /work/source/backups/nacos
  nacos:
    - url: http://test.beinet.cn/nacos/
      username: readonly
      password: 123456
    - url: http://prod.beinet.cn/nacos/
      username: readonly
      password: 123456
