server:
  port: 8999
  servlet:
    context-path: /sql

spring:
  application:
    name: "code-generate"         # 程序name，建议配置，方便统一的服务管理
  profiles:
    active: dev

  # mysql连接信息配置
  datasource:
    url: jdbc:mysql://127.0.0.1:8306/ops?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&socketTimeout=2000&connectTimeout=2000&rewriteBatchedStatements=true&useSSL=false&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    default-property-inclusion: always  #为空也序列化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    mapper:
      accept_case_insensitive_properties: true

  ldap:
    urls: ldap://beinet.cn:389
    base: OU=OrgUnit,DC=beinet,DC=cn
    email-domain: "beinet.cn"  # 登录ldap时，如果配置了此域名，会在用户名后添加@域名

logging:
  level:
    cn.beinet.codegenerate.configs.LdapLoginFilter: debug

ip-filter:
  white-ip: # 客户端IP，以这些IP为前缀时，才允许访问
    - 127.
    - 10.
    - 192.168.
    - 0:0:0:0:0:0:0:1
    - 8.217.76.130
  exclude-url: # 这些url前缀，不进行IP过滤
    - /test
    - /test2

# api调用使用的认证 ak/sk
sdk:
  app-key: sdk
  secure-key: 123456

third-login-info:
  # 未登录时，要跳转到哪里去登录
  login-url: https://login.dingtalk.com/oauth2/auth?response_type=code&client_id=${ird-login-info.app-key}&scope=openid
  # 登录成功时，跳回到哪个地址？通常是本服务的域名+接收token的地址
  callback-url: /authCallback
  # 跟随url传递到登录方，再通过回调传递回来的参数，业务方自用
  callback-para: xxxxxxxxx
  app-key: aaa
  app-secret: bbb


cloud:
  # 用于阿里云cdn操作的ak/sk
  ali-cdn:
    ak: 11
    sk: 22
    exe-path: D:\\aaa\\aliyun.exe

backup:
  enable: false
  # gitlab表示备份文件 存储到哪里
  gitlab:
    url: https://git.beinet.cn/backups.git
    username: beiliang_you
    password: 123456
    rootDir: /work/source/backups
  # 要备份的nacos服务列表，备份每个nacos所有命名空间的配置
  nacos:
    enable: false
    backDir: /work/source/backups/nacos
    sites:
      - url: http://test.beinet.cn/nacos/
        username: readonly
        password: 123456
      - url: http://prod.beinet.cn/nacos/
        username: readonly
        password: 123456
  # 要备份的mysql服务列表，备份每个mysql的表结构和数据增长情况
  mysql:
    enable: false
    backDir: /data/app/backups/mysql
    instances:
      - ip: 10.2.5.2
        port: 3306
        username: readonly
        password: 123456
      - ip: 10.2.5.3
        port: 3306
        username: readonly
        password: 123456
  # 要备份的jenkins服务列表，备份每个job的xml配置
  jenkins:
    enable: false
    backDir: /data/app/backups/jenkins
    sites:
      - url: http://10.100.72.165:8080/
        username: beinet
        password: 123456
  # 要备份的目录或文件列表
  files:
    enable: false
    backDir: /data/app/backups/backFiles # 备份到哪里
    paths:
      - /etc/nginx                 # 要备份的目录或文件
      - /etc/supervisord.conf
      - /etc/supervisord.d

data-clean:
  enable: false
  mysql:
    - ip: 127.0.0.1           # 数据库IP
      enable: false           # 是否允许当前实例进行数据清理
      port: 8306              # 数据库端口
      username: root          # 数据库登录账号
      password: 123456        # 数据库登录密码
      database: ops           # 要清理的数据库名
      back-to-db: ops-bak     # 全局备份库名，备份数据放到哪个数据库名（同一IP实例下的另一个数据库），为空使用当前数据库
      tables:
        # 配置说明:
        # 1、根据配置的时间字段、保留天数，查找到要处理的记录主键最大值
        # SELECT MAX(key-field) maxId FROM [table-name] FORCE INDEX(force-index-name) WHERE [time-field]< 【now() - keep-days】
        # 2、根据主键maxId进行数据备份
        # INSERT INTO [back-to-db].[table-name]_bak[YearMonth] SELECT 字段列表 FROM [table-name] WHERE [key-field]<=maxId AND [other-condition]
        # 3、根据主键maxId，进行数据删除，每次只删除10000行，直到返回0行为止
        # DELETE FROM [table-name] WHERE [key-field]<=maxId AND [other-condition] LIMIT 10000

        - table-name: table1                # 要清理的表名
          enable: false                     # 是否允许当前表进行数据清理
          key-field: id                     # 主键字段名，只支持自增字段 或 雪花算法这种递增值，只支持单个key
          time-field: create_date           # 用于时间筛选的字段名,通常为记录入库时间或更新时间
          force-index-name: idx_create      # 可空，有时mysql会不使用索引，有此配置表示强制使用该索引进行查询。注：索引必须存在，否则会报错
          other-condition: ""               # 进行备份或删除的数据，需要的其它sql筛选条件, 可以以and或or开头，也可以不加开头
          need-backup: false                # true表示先备份再删除，false表示不备份直接删除
          keep-days: 21                     # 要保留的记录天数，超过该时长的数据，进行删除
          back-hours: 5-23,0-2              # 执行清理的小时范围，[0,4-10,15-23] 表示0点，4点到10点，15到23点; 为空表示0-23

        - table-name: table2
          enable: false
          key-field: id
          time-field: create_date
          force-index-name: idx_create
          other-condition: ""
          need-backup: false
          keep-days: 21
          back-hours: 5-23,0-2
