server:
  port: 8080
  servlet:
    context-path: /sql

spring:
  application:
    name: "code-generate"         # 程序name，建议配置，方便统一的服务管理
  profiles:
    active: dev

  # mysql连接信息配置
  datasource:
    url: jdbc:mysql://10.2.5.2:3306/assets?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&socketTimeout=2000&connectTimeout=2000&rewriteBatchedStatements=true&useSSL=false&serverTimezone=Asia/Shanghai&useSSL=false
    username: beinet
    password: beinet.cn
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    default-property-inclusion: always  #为空也序列化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    mapper:
      accept_case_insensitive_properties: true

  ldap:
    urls: ldap://beinet.cn:389
    base: OU=OrgUnit,DC=beinet,DC=cn

logging:
  level:
    cn.beinet.codegenerate.configs.LdapLoginFilter: debug

sdk:
  app-key: sdk
  secure-key: 123456

backup:
  # gitlab表示备份文件 存储到哪里
  gitlab:
    url: https://git.beinet.cn/backups.git
    username: beiliang_you
    password: 123456
    rootDir: /work/source/backups
  # 要备份的nacos服务列表，备份每个nacos所有命名空间的配置
  nacos:
    enable: true
    backDir: /work/source/backups/nacos
    sites:
      - url: http://test.beinet.cn/nacos/
        username: readonly
        password: 123456
      - url: http://prod.beinet.cn/nacos/
        username: readonly
        password: 123456
  # 要备份的mysql服务列表，备份每个mysql的表结构和数据增长情况
  mysql:
    enable: true
    backDir: /data/app/backups/mysql
    instances:
      - ip: 10.2.5.2
        port: 3306
        username: readonly
        password: 123456
      - ip: 10.2.5.3
        port: 3306
        username: readonly
        password: 123456
  # 要备份的jenkins服务列表，备份每个job的xml配置
  jenkins:
    enable: true
    backDir: /data/app/backups/jenkins
    sites:
      - url: http://10.100.72.165:8080/
        username: beinet
        password: 123456
  # 要备份的目录或文件列表
  files:
    enable: true
    backDir: /data/app/backups/backFiles # 备份到哪里
    paths:
      - /etc/nginx                 # 要备份的目录或文件
      - /etc/supervisord.conf
      - /etc/supervisord.d
