server:
  port: 8080

spring:
  application:
    name: "code-generate"         # 程序name，建议配置，方便统一的服务管理

  # mysql连接信息配置
  datasource:
    url: jdbc:mysql://10.2.5.2:3306/assets?characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: beinet
    password: beinet.cn
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    default-property-inclusion: always  #为空也序列化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    mapper:
      accept_case_insensitive_properties: true

  ldap:
    urls: ldap://beinet.cn:389
    username: cn=ldapauth,${spring.ldap.base}
    password: beinet.cn
    base: OU=OrgUnit,DC=beinet,DC=cn